'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by wsdl, Version=2.0.50727.42.
'
Namespace ASPItalia.Books.Web.Chapter20
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"), _
     System.Diagnostics.DebuggerStepThroughAttribute(), _
     System.ComponentModel.DesignerCategoryAttribute("code"), _
     System.Web.Services.WebServiceBindingAttribute(Name:="WeatherServiceSoap", [Namespace]:="http://webservices.aspitalia.com/WeatherService")> _
    Partial Public Class WeatherServiceProxy
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol

        Private GetTemperatureOperationCompleted As System.Threading.SendOrPostCallback

        '''<remarks/>
        Public Sub New()
            MyBase.New()
            Me.Url = "http://localhost:1324/CS/WeatherService.asmx"
        End Sub

        '''<remarks/>
        Public Event GetTemperatureCompleted As GetTemperatureCompletedEventHandler

        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://webservices.aspitalia.com/WeatherService/GetTemperature", RequestNamespace:="http://webservices.aspitalia.com/WeatherService", ResponseNamespace:="http://webservices.aspitalia.com/WeatherService", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)> _
        Public Function GetTemperature(ByVal cityName As String) As Double
            Dim results() As Object = Me.Invoke("GetTemperature", New Object() {cityName})
            Return CType(results(0), Double)
        End Function

        '''<remarks/>
        Public Function BeginGetTemperature(ByVal cityName As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("GetTemperature", New Object() {cityName}, callback, asyncState)
        End Function

        '''<remarks/>
        Public Function EndGetTemperature(ByVal asyncResult As System.IAsyncResult) As Double
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0), Double)
        End Function

        '''<remarks/>
        Public Overloads Sub GetTemperatureAsync(ByVal cityName As String)
            Me.GetTemperatureAsync(cityName, Nothing)
        End Sub

        '''<remarks/>
        Public Overloads Sub GetTemperatureAsync(ByVal cityName As String, ByVal userState As Object)
            If (Me.GetTemperatureOperationCompleted Is Nothing) Then
                Me.GetTemperatureOperationCompleted = AddressOf Me.OnGetTemperatureOperationCompleted
            End If
            Me.InvokeAsync("GetTemperature", New Object() {cityName}, Me.GetTemperatureOperationCompleted, userState)
        End Sub

        Private Sub OnGetTemperatureOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetTemperatureCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg, System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetTemperatureCompleted(Me, New GetTemperatureCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub

        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")>  _
    Public Delegate Sub GetTemperatureCompletedEventHandler(ByVal sender As Object, ByVal e As GetTemperatureCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetTemperatureCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Double
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Double)
            End Get
        End Property
    End Class
End Namespace
